# Generated by Django 5.0.6 on 2024-06-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_order_customer_cart_profile_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
